//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Guest_tbl
    {
        public int id { get; set; }

        [Required(ErrorMessage ="Enter Name !")]      
        public string Name { get; set; }

        [Required(ErrorMessage = "Enter Email !")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter Phone Number !")]
        public string Phone { get; set; }
    }
}
